name: XCS224N_CUDA
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.8
  - numpy=1.24.3
  - scipy=1.10.1
  - scikit-learn=1.3.0
  - matplotlib=3.7.2
  - tqdm=4.66.2
  - docopt=0.6.2
  - notebook=7.0.8
  - pip=23.3.1
  - tensorboard
  - pip:
    - sentencepiece
    - sacrebleu
    - nltk
    - timeout_decorator
    - "--find-links https://download.pytorch.org/whl/torch_stable.html"
    - torch==2.3.0+cu118